# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6849f947befef323f745cb297aeae3f5830012363f72046f1cb580e1efad51c2592a7380ed81f04f2ac4c073aae27cd166bbfab967e8923d7060bc612c3e2f4d

test:
  secret_key_base: 104247faa154c8ebbb6d765c82f2da133f31018f9a5afa179858b3b8355911089f4f98b9714cdfde8a025f36db3118c694d35f4a6bfe4fb895344165002111b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
